name: note
description: "Note."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  freezed_annotation: ^2.4.1
  go_router: ^12.1.1
  hooks_riverpod: ^2.4.9
  json_annotation: ^4.8.1
  path_provider: ^2.1.1
  riverpod_annotation: ^2.3.3
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  freezed: ^2.4.5
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
